theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: false
  menu:
    primary:
      level_2:
        title:
          active: true

  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-white.svg"