[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/acteurs-de-l-ess/"
to = "/mon-offre/acteursde-l-economie-sociale-et-solidaire/"

[[redirects]]
from = "/entreprises-engagees/"
to = "/mon-offre/entreprises-engagees/"

[[redirects]]
from = "/actualites/2024-07-15-et-toi-tu-fais-quoi-dans-la-vie/"
to = "/actualites/2019-12-10-et-toi-tu-fais-quoi-dans-la-vie/"

[[redirects]]
from = "/actualites/2024-07-15-reboot/"
to = "/actualites/2021-10-16-de-tribunes-en-actions-reboot/"

[[redirects]]
from = "/actualites/2022-06-20-lancement-de-communication-et-democratie/"
to = "/actualites/2022-06-01-lancement-de-communication-et-democratie/"

[[redirects]]
from = "/celine-reveillac/actualites/"
to = "/equipe/celine-reveillac/actualites/"

[[redirects]]
from = "/equipe-editoriale/"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/formation-enseignement/"
to = "/mon-offre/enseignement-superieur/"

[[redirects]]
from = "/actualites/2024-07-15-tous-daccord/"
to = "/actualites/2020-12-12-tous-daccord/"

[[redirects]]
from = "/celine-reveillac/"
to = "/equipe/celine-reveillac/"

[[redirects]]
from = "/mon-offre/acteurs-de-l-ess/"
to = "/mon-offre/acteursde-l-economie-sociale-et-solidaire/"

[[redirects]]
from = "/formation/"
to = "/mon-offre/enseignement-superieur/"

[[redirects]]
from = "/projets/"
to = "/conseil/"

